import os
# Credentials you get from registering a new application
client_id = os.environ.get("CLIENT_ID")
client_secret = os.environ.get("CLIENT_SECRET")
#redirect_uri = "https://nimpf.akimbo.com"
# OAuth endpoints given in the Google API documentation
authorization_base_url = "https://accounts.google.com/o/oauth2/v2/auth"
token_url = "https://www.googleapis.com/oauth2/v4/token"
refresh_url = token_url
scope = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
    "openid",
    "https://www.googleapis.com/auth/gmail.settings.basic",
]


goldlist = [
 "Dave Ramsey",
 "Tim Ferris",
 "Seth's blog",
 "Andreesen Horowitz",
 "altMBA",
 "Gretchen Rubin",
 "TED.org",
 "Sarah Jones",
 "Wait But Why",
 "HelpScout",
 "Feedblitz",
 "Freakonomics",
 "Brene Brown",
 "Simon Sinek",
 "A Learning a Day",
 "Austin Kleon",
 "The Hustle",
 "Dense Discovery",
 "O'Reilly",
 "Continuations",
 "Albert Wenger",
 "AVC",
 "CGP Grey",
 "dailydad.com",
 "Kevin Kelly (The Technium update)",
 "Craig Mod",
 "Marie Forleo",
 "Steve Pressfield",
 "StoryGrid / Shawn Coyne",
 "Bernadette Jiwa",
 "Swiss Miss",
 "Gaping Void",
 "Behance / 99u",
 "Debbie Millman",
 "NYPL",
 "Electronic Frontier Fondation",
 "Julian Shapiro",
 "Renee DiResta",
 "Adam Silver",
 "Amanda Palmer",
 "John Green",
 "Hank Green",
 "Stewart Brand / The Long Now Foundation",
 "Miranda July",
 "Kenji Lopez-Alt",
 "UserOnboarding",
 "Ta-Nehisi Coates",
 "Discourse",
 "Jeff Atwood / Coding Horror",
 "charity: water",
 "Patreon",
 "Armin Ronacher",
 "Andrew Chen",
 "Paul Jarvis",
 "James Clear",
 "Chris Messina",
 "Sarah Lacy / Pando ",
 "Sarah Lacy / Chairman Mom",
 "Maria Popova / Brain Pickings",
 "The Simm",
 "The Broadsheet",
 "The Daily Good",
 "Robin Sloan",
 "Ms. Magazine",
 "SoapBox",
 "Buster Benson",
 "Jessica Valenti / Feministing",
 "Courtney Martin",
 "John Cary",
 "Krista Tippett / On Being",
 "Ann Friedman",
 "Jonathan Haidt",
 "Dan Ariely",
 "Dan Pink",
 "SY Partners",
 "Yuval Noah Harari",
 "XKCD",
 "Marco Arment",
 "Joel Spolsky",
 "Ryan Delk",
 "Postlight",
 "Candy Chang",
 "James Victore",
 "Civic Hall",
 "Shane Parrish",
 "Angela Duckworth",
 "Adam Grant",
]
